# Pius Gumo
# 10/08/2023
# Container for the Python Flask Application with a MySQL Database and Web Server

version: "3.1"

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
  web-app:
    build: .
    command: python app.py
    volumes:
      - .:/code
    depends_on:
      - db
volumes:
  db_data:
